/**
 * GENERATED by docs/legal/generate.mjs from docs/legal/privacy-policy.md. Do not edit by hand: change the Markdown and run
 * `node docs/legal/generate.mjs` (CI fails with `--check` when this file is out of date).
 */
import { colors, spacing, typography } from '@festival/ui';
import * as Linking from 'expo-linking';
import { router, Stack } from 'expo-router';
import * as WebBrowser from 'expo-web-browser';
import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

import { SUPPORT_EMAIL } from '@/src/config/app-info';

type Span =
  | { kind: 'text' | 'bold'; text: string }
  | { kind: 'route'; text: string; href: string }
  | { kind: 'url'; text: string; href: string };

type Block = { type: 'h2' | 'h3' | 'p' | 'li'; spans: Span[] };

const TITLE = "Privacy Policy";
const UPDATED = "October 5, 2026";
const SUPPORT_EMAIL_TOKEN = '__SUPPORT_EMAIL__';
/** docs/legal/values.json `supportEmail`, used only when the build has no EXPO_PUBLIC_SUPPORT_EMAIL. */
const SUPPORT_EMAIL_FALLBACK: string | null = null;
const SUPPORT_ADDRESS = SUPPORT_EMAIL ?? SUPPORT_EMAIL_FALLBACK;

const CONTENT: Block[] = [
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "Festie is a festival planning app operated by __LEGAL_NAME__ (\"Festie\", \"we\", \"us\"). This policy explains what information the Festie app and its servers handle, why, who can see it, how long we keep it and the choices you have. If you have a question, email __SUPPORT_EMAIL__."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "Summary"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "We collect only what Festie needs to work: your email address, the profile you choose, your festival plans and crews, the meetups and photos you post and, only while you turn it on, your location."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "No ads, no tracking, and no analytics, crash-reporting or advertising SDKs. We do not sell your personal information or share it for advertising. The only counting is of app installations: Mapbox (maps) and Expo (app updates) count them with a random identifier that is not linked to your account (section 4)."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Your live location is shown only to the crew you choose, only while Festie is open, and is visible to your crew for at most 15 minutes after the last update, then deleted."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "You can delete your account at any time in Settings, Delete account."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "1. Information we collect"
      }
    ]
  },
  {
    "type": "h3",
    "spans": [
      {
        "kind": "text",
        "text": "Account"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Email address."
      },
      {
        "kind": "text",
        "text": " Used to send your sign-in code and to identify your account. Other Festie users never see your email address."
      }
    ]
  },
  {
    "type": "h3",
    "spans": [
      {
        "kind": "text",
        "text": "Profile"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Display name and avatar."
      },
      {
        "kind": "text",
        "text": " The name you choose (up to 40 characters) and an avatar made of your initials, an emoji or a colour. Festie has no profile photos. Members of crews you belong to see your name and avatar."
      }
    ]
  },
  {
    "type": "h3",
    "spans": [
      {
        "kind": "text",
        "text": "Festival plans"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Festivals you follow."
      },
      {
        "kind": "text",
        "text": " Visible only to you."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Sets you pick."
      },
      {
        "kind": "text",
        "text": " Members of your crews for the same festival see your picks in the crew schedule."
      }
    ]
  },
  {
    "type": "h3",
    "spans": [
      {
        "kind": "text",
        "text": "Crews"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Crews you create or join"
      },
      {
        "kind": "text",
        "text": " and your role in each (admin or member). Crew members see the crew name, its invite code and the list of members."
      }
    ]
  },
  {
    "type": "h3",
    "spans": [
      {
        "kind": "text",
        "text": "Meetups"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Meetups you create:"
      },
      {
        "kind": "text",
        "text": " title, time, optional stage, optional pin on the festival map and optional notes (up to 500 characters). Members of that crew see them."
      }
    ]
  },
  {
    "type": "h3",
    "spans": [
      {
        "kind": "text",
        "text": "Totem photos"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Photos you choose or take for a meetup."
      },
      {
        "kind": "text",
        "text": " Before a photo leaves your phone, Festie converts it to a JPEG and removes its metadata, such as GPS location, camera details and the time it was taken. Photos are stored privately: only members of that crew can view them, through links that expire after an hour."
      }
    ]
  },
  {
    "type": "h3",
    "spans": [
      {
        "kind": "text",
        "text": "Live location, only while you share it"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "When you turn on location sharing for a crew, Festie sends your precise location (latitude, longitude, accuracy and direction) while the app is open on your screen: as you move and about every 2 minutes. Festie never collects your location in the background."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Sharing stops automatically at the end of the time you chose (1, 4 or 8 hours, or \"Until I stop\", which still ends after 24 hours), and also when you turn it off, leave the crew, are removed from it or sign out."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Your position is visible to your crew for at most 15 minutes after the last update, then deleted. Turning sharing off deletes it straight away (if your phone is offline at that moment, it simply expires)."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "If you allow location access, the map can also show your own position as a dot. That stays on your phone and is not sent to us."
      }
    ]
  },
  {
    "type": "h3",
    "spans": [
      {
        "kind": "text",
        "text": "Reports and blocks"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Reports."
      },
      {
        "kind": "text",
        "text": " When you report a person, crew, meetup or photo, we store the reason you chose, any details you add (up to 500 characters), what you reported, a copy of the reported text at that moment (for example a name or meetup title) and that the report came from your account. The person you report is not told who reported them."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Blocks."
      },
      {
        "kind": "text",
        "text": " We store who you have blocked. The person you block is not told."
      }
    ]
  },
  {
    "type": "h3",
    "spans": [
      {
        "kind": "text",
        "text": "Technical information"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "To run sign-in and the app's server, our hosting provider processes technical information such as your IP address, the time of each request and basic information your device sends with it (for example the operating system)."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Sign-in logs."
      },
      {
        "kind": "text",
        "text": " Each sign-in, code request, session refresh and sign-out is logged with your email address, your IP address and the time. Each active sign-in session also records the IP address and device information of the phone using it. We use these records only to keep accounts secure and investigate abuse."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "To prevent abuse, we keep short-lived rate-limit records: an account identifier, or the IP address of a device that enters a sign-in code we cannot verify, with a timestamp. They are deleted about a day after they are created."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "When Festie starts, it checks Expo's update service for fixes to the app. These requests include the app version, platform and a random identifier for the installation that the update system creates. They contain no account information."
      }
    ]
  },
  {
    "type": "h3",
    "spans": [
      {
        "kind": "text",
        "text": "On your phone"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "To work offline at a festival, Festie keeps your sign-in session, a copy of your schedule, crews and meetups, changes waiting to sync, your reminders and your settings in the app's private storage on your phone, which iOS protects with its standard data protection. Signing out or deleting your account in the app removes your account data from the phone. If you are signed out without doing it yourself (for example, your sign-in expires or you deleted your account on another device), Festie keeps that copy, including changes not yet synced, so nothing is lost: it cannot be viewed while you are signed out, and it is removed when you sign in again and then sign out, when a different account (including a new one after a deletion) signs in on the phone, or when you delete the app. Deleting the app removes everything."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Set and meetup reminders are scheduled on your phone as local notifications. We do not use push notification servers."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "2. What we do not collect"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Your contacts or address book."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Your location in the background, or at any time you are not sharing it with a crew."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Microphone or audio. Festie never asks for microphone access."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Your advertising identifier. Festie does not track you across other companies' apps or websites, so it never shows the App Tracking Transparency prompt."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Analytics, crash-reporting or advertising data. Festie contains no analytics, crash-reporting or advertising SDKs, and it turns off the map's optional Mapbox telemetry. The only counting is the installation count described in section 4, with a random identifier that is not linked to your account."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Payment information. Festie is free and has no purchases."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "3. How we use information"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "We use information only to provide and protect Festie:"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "to sign you in and keep you signed in;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "to show your profile, picks, meetups, photos and, while you share it, your location to your crews;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "to keep your plans available offline and in sync;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "to schedule reminders on your phone;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "to review reports and enforce our "
      },
      {
        "kind": "route",
        "text": "Terms of Use",
        "href": "/legal/terms-of-use"
      },
      {
        "kind": "text",
        "text": ", including an automatic filter that rejects disallowed words in names, crew names and meetup text;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "to prevent abuse and keep the service secure, for example with rate limits;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "to answer your support requests and meet legal obligations."
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "We do not use your information for advertising or profiling, we do not sell it, and we make no automated decisions about you with legal or similarly significant effects."
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "If you are in the European Economic Area or the United Kingdom, we rely on these legal bases: performing our contract with you (running the app you signed up for), our legitimate interests in keeping Festie safe and preventing abuse (moderation, security, rate limits), your consent for location sharing and for camera and photo access (you can withdraw it at any time by turning sharing off or changing the permission in iOS Settings), and compliance with legal obligations."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "4. Who can see your information"
      }
    ]
  },
  {
    "type": "h3",
    "spans": [
      {
        "kind": "text",
        "text": "Your crews"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "Members of a crew see your display name and avatar, your picks for that crew's festival, the meetups and totem photos you post in that crew and, while you share it with that crew, your location. If you block someone, or they block you, neither of you sees the other's location, meetups (including their totem photos) or picks."
      }
    ]
  },
  {
    "type": "h3",
    "spans": [
      {
        "kind": "text",
        "text": "Us"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "We can access the data on our servers to operate Festie, answer support requests and review reports."
      }
    ]
  },
  {
    "type": "h3",
    "spans": [
      {
        "kind": "text",
        "text": "Service providers"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "These companies process data for us, only to run Festie. Each provider may use the information only to provide its service to us, is bound by contract (including data processing terms where the law requires them) to protect it at least as well as this policy does, and may not use it for its own purposes."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Supabase"
      },
      {
        "kind": "text",
        "text": " hosts our database, sign-in, photo storage and server functions, and stores all account and app data, in __SUPABASE_REGION__."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "__EMAIL_PROVIDER__"
      },
      {
        "kind": "text",
        "text": " delivers sign-in code emails. It receives your email address and the email itself."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Mapbox"
      },
      {
        "kind": "text",
        "text": " provides map tiles when you open the map or download a festival map for offline use. Your device sends Mapbox its IP address, basic device information, the map area being loaded and a random identifier for the installation that Mapbox uses to count active users, but no account information."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Expo"
      },
      {
        "kind": "text",
        "text": " provides the app update service described in section 1 and uses its random installation identifier to count how many installations receive each update. It receives no account information."
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "Apple distributes Festie through the App Store under Apple's own privacy policy. Festie does not use Apple's or Expo's push notification services."
      }
    ]
  },
  {
    "type": "h3",
    "spans": [
      {
        "kind": "text",
        "text": "Others"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "We disclose information to authorities only if the law requires it or where necessary to protect someone's safety. If Festie is transferred to another operator, that operator must keep honouring this policy."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "5. How long we keep information"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Live location:"
      },
      {
        "kind": "text",
        "text": " visible to your crew for at most 15 minutes after the last update, then deleted. Turning sharing off (while online), leaving the crew or being removed deletes it immediately."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Rate-limit records:"
      },
      {
        "kind": "text",
        "text": " about a day after they are created."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Account, profile, picks, followed festivals, crews, meetups, photos and blocks:"
      },
      {
        "kind": "text",
        "text": " until you delete them or delete your account."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Meetups in a crew you leave:"
      },
      {
        "kind": "text",
        "text": " they stay visible to that crew until a crew admin removes them or you delete your account."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Crews:"
      },
      {
        "kind": "text",
        "text": " deleted automatically, with their meetups, when the last member leaves. Their photos are deleted with them when the last member deletes their account, and otherwise by routine cleanup within about a week."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Totem photos:"
      },
      {
        "kind": "text",
        "text": " deleted when you replace them or delete the meetup. Photo files left behind, for example by a deleted crew or an interrupted upload, are removed by routine cleanup within about a week."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Reports:"
      },
      {
        "kind": "text",
        "text": " kept as a moderation record. If you delete your account, reports you sent are kept without your name. Reports about you or your content keep the copy of the reported text taken at the time."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Banned accounts:"
      },
      {
        "kind": "text",
        "text": " if we ban an account for breaking our Terms of Use, we remove it from every crew and delete its meetups, totem photos and shared location. We keep its profile, sign-in account and email address, and any other content it posted that we have not removed, as a record of the ban and to stop it signing in again."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Sign-in logs:"
      },
      {
        "kind": "text",
        "text": " at most 90 days, then deleted automatically, including after you delete your account. The record of a sign-in session (its IP address and device information) is kept while the session can be used, and deleted when you sign out on that device while online or delete your account."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Logs and backups:"
      },
      {
        "kind": "text",
        "text": " our hosting provider keeps other operational logs, such as server request logs, for at most 90 days, and database backups for a limited period. Deleted information can remain in backups until they expire."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "6. Deleting your account"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "You can delete your account in the app: open Settings (your avatar on the Fests screen), tap Delete account, type DELETE and tap Delete my account. You need an internet connection. Deletion happens on our servers straight away and permanently removes:"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "your profile: name, avatar and email address, and your sign-in account;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "your crew memberships. If you are a crew's only admin, the longest-standing member becomes admin; crews left with no members are deleted with their meetups and photos;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "the meetups and totem photos you created;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "your schedule picks and followed festivals;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "your shared location and the people you blocked."
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "Festie then stops location sharing, cancels your reminders and clears your account data from the phone. Changes that had not synced yet are discarded. Reports you sent are kept without your name so we can finish reviewing them. Sign-in log entries that mention your email address (section 1) are not part of your account; they are deleted automatically when they reach the 90-day limit in section 5. You can sign up again later with the same email, but nothing is restored. You can also ask us to delete your account by emailing __SUPPORT_EMAIL__ from the address you sign in with."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "7. Security"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "All connections between the app and our servers are encrypted (HTTPS/TLS)."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Database rules allow each account to read only its own data and what is shared in its crews. Automated tests check these rules on every change."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Totem photos are stored privately and shown only through short-lived links. Your email address is never readable by other users."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Your sign-in session stays in the app's private storage on your phone, protected by iOS data protection."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Sign-in, invites, reports and other sensitive actions are rate-limited."
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "No system is perfectly secure. If you find a security problem, please email __SUPPORT_EMAIL__."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "8. Children"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "Festie is not directed to children under 13, and you must be at least 13 to use it (see our "
      },
      {
        "kind": "route",
        "text": "Terms of Use",
        "href": "/legal/terms-of-use"
      },
      {
        "kind": "text",
        "text": "). We do not knowingly collect personal information from children under 13. If you believe a child under 13 has given us personal information, email __SUPPORT_EMAIL__ and we will delete it."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "9. Your rights and choices"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Change your profile"
      },
      {
        "kind": "text",
        "text": " at any time in Settings, Profile."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Delete your account"
      },
      {
        "kind": "text",
        "text": " in Settings, Delete account (see section 6)."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Location sharing"
      },
      {
        "kind": "text",
        "text": " is off until you turn it on for a crew, and you can stop it at any time on the map or in Settings. You can also turn off location access for Festie in iOS Settings."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Camera, photos and notifications"
      },
      {
        "kind": "text",
        "text": " are used only when you choose, and you can turn them off in iOS Settings."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "bold",
        "text": "Access and copies."
      },
      {
        "kind": "text",
        "text": " Email __SUPPORT_EMAIL__ for a copy of your information."
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "Depending on where you live (for example in the EEA, the UK or California), you may have the right to access, correct, delete or receive a portable copy of your personal information, to restrict or object to its processing, to withdraw consent, and to complain to your data protection authority. We will answer within the time the law requires, and we may need to confirm the request comes from your account's email address. We do not sell or share personal information as those terms are defined in California law, and we will not treat you differently for exercising your rights."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "10. International transfers"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "Our servers are in __SUPABASE_REGION__, and our service providers may process information in other countries, including the United States. Where the law requires it, these transfers are protected by safeguards such as the European Commission's Standard Contractual Clauses."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "11. Changes to this policy"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "When we change this policy we will update the date at the top. If a change is significant, Festie will ask you to review and agree to the updated documents in the app before you continue."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "12. Contact"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "__LEGAL_NAME__, __POSTAL_ADDRESS__"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "Email: __SUPPORT_EMAIL__"
      }
    ]
  }
];

function openUrl(href: string): void {
  if (href.startsWith('https://')) {
    WebBrowser.openBrowserAsync(href).catch(() => Linking.openURL(href).catch(() => undefined));
  } else {
    Linking.openURL(href).catch(() => undefined);
  }
}

/** Plain text, with the support-email variable replaced by the configured, tappable address. */
function renderText(text: string, key: string): React.ReactNode {
  const address = SUPPORT_ADDRESS;
  if (!address || !text.includes(SUPPORT_EMAIL_TOKEN)) {
    return text;
  }
  return text.split(SUPPORT_EMAIL_TOKEN).map((part, index) => (
    <React.Fragment key={`${key}-${index}`}>
      {index > 0 ? (
        <Text style={styles.link} accessibilityRole="link" onPress={() => openUrl(`mailto:${address}`)}>
          {address}
        </Text>
      ) : null}
      {part}
    </React.Fragment>
  ));
}

function renderSpans(spans: Span[], blockKey: string): React.ReactNode[] {
  return spans.map((span, index) => {
    const key = `${blockKey}-${index}`;
    switch (span.kind) {
      case 'bold':
        return (
          <Text key={key} style={styles.bold}>
            {renderText(span.text, key)}
          </Text>
        );
      case 'route':
        return (
          <Text key={key} style={styles.link} accessibilityRole="link" onPress={() => router.push(span.href as never)}>
            {span.text}
          </Text>
        );
      case 'url':
        return (
          <Text key={key} style={styles.link} accessibilityRole="link" onPress={() => openUrl(span.href)}>
            {span.text}
          </Text>
        );
      default:
        return <React.Fragment key={key}>{renderText(span.text, key)}</React.Fragment>;
    }
  });
}

export default function PrivacyPolicyScreen() {
  return (
    <>
      <Stack.Screen options={{ title: TITLE }} />
      <ScrollView style={styles.scroll} contentContainerStyle={styles.container}>
        <Text style={styles.updated}>Last updated: {UPDATED}</Text>
        {CONTENT.map((block, index) => {
          const key = `b${index}`;
          if (block.type === 'h2' || block.type === 'h3') {
            return (
              <Text key={key} style={block.type === 'h2' ? styles.h2 : styles.h3} accessibilityRole="header">
                {renderSpans(block.spans, key)}
              </Text>
            );
          }
          if (block.type === 'li') {
            return (
              <View key={key} style={styles.listItem}>
                <Text style={styles.bullet} importantForAccessibility="no" accessibilityElementsHidden>
                  •
                </Text>
                <Text style={[styles.body, styles.listText]}>{renderSpans(block.spans, key)}</Text>
              </View>
            );
          }
          return (
            <Text key={key} style={styles.body}>
              {renderSpans(block.spans, key)}
            </Text>
          );
        })}
      </ScrollView>
    </>
  );
}

const styles = StyleSheet.create({
  scroll: { flex: 1, backgroundColor: colors.background },
  container: { padding: spacing.lg, paddingBottom: spacing.xxxl + spacing.xl, gap: spacing.sm },
  updated: { ...typography.label, color: colors.textSecondary, marginBottom: spacing.sm },
  h2: { ...typography.heading, color: colors.textPrimary, fontSize: 21, lineHeight: 27, marginTop: spacing.lg },
  h3: { color: colors.textPrimary, fontSize: 16, fontWeight: '800', lineHeight: 22, marginTop: spacing.sm },
  body: { color: colors.textPrimary, fontSize: 15, lineHeight: 22 },
  bold: { fontWeight: '700' },
  link: { color: colors.link, fontWeight: '600', textDecorationLine: 'underline' },
  listItem: { flexDirection: 'row', gap: spacing.sm, paddingLeft: spacing.xs },
  bullet: { color: colors.textPrimary, fontSize: 15, lineHeight: 22 },
  listText: { flex: 1 },
});
