/**
 * GENERATED by docs/legal/generate.mjs from docs/legal/terms-of-use.md. Do not edit by hand: change the Markdown and run
 * `node docs/legal/generate.mjs` (CI fails with `--check` when this file is out of date).
 */
import { colors, spacing, typography } from '@festival/ui';
import * as Linking from 'expo-linking';
import { router, Stack } from 'expo-router';
import * as WebBrowser from 'expo-web-browser';
import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

import { SUPPORT_EMAIL } from '@/src/config/app-info';

type Span =
  | { kind: 'text' | 'bold'; text: string }
  | { kind: 'route'; text: string; href: string }
  | { kind: 'url'; text: string; href: string };

type Block = { type: 'h2' | 'h3' | 'p' | 'li'; spans: Span[] };

const TITLE = "Terms of Use";
const UPDATED = "October 5, 2026";
const SUPPORT_EMAIL_TOKEN = '__SUPPORT_EMAIL__';
/** docs/legal/values.json `supportEmail`, used only when the build has no EXPO_PUBLIC_SUPPORT_EMAIL. */
const SUPPORT_EMAIL_FALLBACK: string | null = null;
const SUPPORT_ADDRESS = SUPPORT_EMAIL ?? SUPPORT_EMAIL_FALLBACK;

const CONTENT: Block[] = [
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "These Terms of Use (\"Terms\") are an agreement between you and __LEGAL_NAME__ (\"Festie\", \"we\", \"us\") for using the Festie app and its services. By creating an account or using Festie you agree to these Terms and confirm you have read our "
      },
      {
        "kind": "route",
        "text": "Privacy Policy",
        "href": "/legal/privacy-policy"
      },
      {
        "kind": "text",
        "text": ". If you do not agree, do not use Festie."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "1. Zero tolerance for objectionable content and abuse"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "Festie has zero tolerance for objectionable content or abusive users; we act on reports within 24 hours by removing content and ejecting offenders. You can report any person, crew, meetup or photo and block any person from within the app."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "2. Who can use Festie"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "You must be at least 13 years old. If you are under the age of majority where you live, you may use Festie only with the permission of a parent or guardian, who agrees to these Terms for you."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "You must not use Festie if we have banned you, or if the law where you live does not allow you to."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "You need a valid email address that you control. Keep access to it secure: anyone who can read your email can sign in to your account. You are responsible for what happens in your account."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "3. What Festie does"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "Festie helps you plan a music festival: build a schedule, see the sets your crew picked, set up meetups and, only when you choose, share your location with a crew. Festie is free and for personal, non-commercial use."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "4. Acceptable use"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "You agree not to:"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "harass, bully, threaten, stalk or intimidate anyone, or use location sharing or meetups to follow or find someone who does not want to be found;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "post content that is hateful, discriminatory, sexually explicit, violent, defamatory, illegal or that promotes self-harm or illegal activity;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "impersonate anyone or misrepresent who you are, including in your display name;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "post someone else's personal information, or photos of people without their permission;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "post spam, advertising or ticket resale offers;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "post content you do not have the right to share, or that infringes anyone's intellectual property, privacy or other rights;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "break the law or help anyone else do so;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "get around blocks, bans, rate limits or other safety and security measures, access accounts or data that are not yours, or probe, scan or overload our systems;"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "scrape, copy or collect data from Festie with automated tools, or reverse engineer the app except where the law allows it."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "5. Your content"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "\"Your content\" means what you add to Festie: your display name and avatar, crew names, meetups, notes and totem photos."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "You keep ownership of your content. You give us a worldwide, non-exclusive, royalty-free licence to host, store, copy, process and display your content only as needed to operate and improve Festie and to show it to the people you share it with (for example, your crew). The licence ends when your content is deleted, except for copies kept in backups for a limited period and content needed for a report we are reviewing."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "You are responsible for your content and promise that you have the right to share it and that it follows these Terms."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "We do not review content before it appears, but an automatic filter rejects disallowed words in names and meetup text, and we review every report. We may remove any content, or restrict any account, that we reasonably believe breaks these Terms or the law."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "6. Reports, blocks and enforcement"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Report content or people with the Report options in the app. We review reports within 24 hours. When content breaks these Terms, we remove it and remove the people responsible from Festie."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Block someone from their name in a crew. You will no longer see their location, meetups (including their totem photos) or picks, and they will not see yours. They are not told. You can unblock them later in Settings."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Crew admins can remove members from their crew."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "We may suspend or permanently ban accounts that break these Terms, without notice where needed to protect others. A banned account loses access at once, is removed from every crew, and its meetups and photos are deleted."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "7. Location sharing"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Location sharing is off until you turn it on for a crew. While it is on, members of that crew can see your position while Festie is open. Your position is visible to your crew for at most 15 minutes after the last update, then deleted."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Only share your location with people you trust, and turn it off whenever you want. Stop sharing and leave the crew, or block the person, if anyone makes you feel unsafe."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Locations can be delayed, inaccurate or missing (for example with a weak signal or when someone closes the app). Do not rely on Festie for your safety or in an emergency: contact festival staff or emergency services."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "8. Festival information"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Festie is an independent app and is not affiliated with or endorsed by any festival, organizer, venue or artist. Festival, stage and artist names are used only to identify them."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "We take schedules from official public sources, but festivals change line-ups, times and stages, sometimes at short notice. Always check official festival sources. We are not responsible for missed sets or other consequences of schedule changes or errors."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Sample festivals in the app are fictional and marked \"Sample\"."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "9. Our app"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "Festie, its design and its software belong to us or our licensors and are protected by law. We give you a personal, revocable, non-transferable, non-exclusive licence to use the app on Apple devices you own or control, under these Terms and the App Store's terms."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "10. Ending your use"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "You can stop using Festie at any time and delete your account in Settings, Delete account."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "We may suspend or end your access if you break these Terms, if the law requires it, or if we stop offering Festie. Where it is reasonable, we will let you know first."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Sections 5 (licence for content in backups and reports), 8, 11, 12 and 14 continue to apply after your use ends."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "11. Disclaimers"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "FESTIE IS PROVIDED \"AS IS\" AND \"AS AVAILABLE\". TO THE FULLEST EXTENT ALLOWED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. WE DO NOT PROMISE THAT FESTIE WILL BE UNINTERRUPTED, ERROR-FREE OR AVAILABLE AT A FESTIVAL, THAT SCHEDULES OR LOCATIONS WILL BE ACCURATE, OR THAT OTHER USERS WILL BEHAVE APPROPRIATELY."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "12. Limitation of liability"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "TO THE FULLEST EXTENT ALLOWED BY LAW, WE ARE NOT LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, OR FOR LOST PROFITS, DATA OR GOODWILL, ARISING FROM YOUR USE OF FESTIE OR FROM OTHER USERS' CONDUCT OR CONTENT. OUR TOTAL LIABILITY FOR ANY CLAIM ABOUT FESTIE IS LIMITED TO 50 US DOLLARS. Some places do not allow these limits, so they may not apply to you; nothing in these Terms limits rights you have under laws that cannot be waived."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "13. Changes to these Terms"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "We may update these Terms. We will change the date at the top and, for significant changes, Festie will ask you to review and agree to the new Terms in the app before you continue. If you do not agree, stop using Festie and delete your account."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "14. Governing law and disputes"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "These Terms are governed by the laws of __GOVERNING_LAW__, without regard to conflict-of-law rules, and disputes will be resolved in the courts of __GOVERNING_VENUE__, unless the law where you live gives you the right to bring a claim in your local courts or under your local law."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "15. Apple App Store terms"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "If you downloaded Festie from the App Store:"
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Your licence to use the app is also governed by Apple's "
      },
      {
        "kind": "url",
        "text": "Licensed Application End User License Agreement",
        "href": "https://www.apple.com/legal/internet-services/itunes/dev/stdeula/"
      },
      {
        "kind": "text",
        "text": " (the \"Standard EULA\"). These Terms add the rules for using our service; if they conflict with the Standard EULA about your licence to the app, the Standard EULA applies."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "These Terms are between you and us, not Apple. We, not Apple, are solely responsible for Festie and its content, for maintenance and support, and for handling any claims about the app, including product liability claims, claims that it fails to meet legal or regulatory requirements, consumer protection claims and intellectual property infringement claims."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Apple has no obligation to provide maintenance or support for Festie. To the extent the law allows, Apple has no warranty obligation for the app; if the app fails to meet an applicable warranty, you may notify Apple, and Apple will refund the purchase price, if any (Festie is free)."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "You confirm that you are not located in a country subject to a U.S. Government embargo or designated as a \"terrorist supporting\" country, and that you are not on any U.S. Government list of prohibited or restricted parties."
      }
    ]
  },
  {
    "type": "li",
    "spans": [
      {
        "kind": "text",
        "text": "Apple and its subsidiaries are third-party beneficiaries of these Terms and may enforce them against you."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "16. General"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "If any part of these Terms is found unenforceable, the rest stays in effect. If we do not enforce a right, we have not waived it. You may not transfer your rights under these Terms; we may transfer ours to a successor operator of Festie. These Terms and our Privacy Policy are the whole agreement between you and us about Festie."
      }
    ]
  },
  {
    "type": "h2",
    "spans": [
      {
        "kind": "text",
        "text": "17. Contact"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "__LEGAL_NAME__, __POSTAL_ADDRESS__"
      }
    ]
  },
  {
    "type": "p",
    "spans": [
      {
        "kind": "text",
        "text": "Email: __SUPPORT_EMAIL__"
      }
    ]
  }
];

function openUrl(href: string): void {
  if (href.startsWith('https://')) {
    WebBrowser.openBrowserAsync(href).catch(() => Linking.openURL(href).catch(() => undefined));
  } else {
    Linking.openURL(href).catch(() => undefined);
  }
}

/** Plain text, with the support-email variable replaced by the configured, tappable address. */
function renderText(text: string, key: string): React.ReactNode {
  const address = SUPPORT_ADDRESS;
  if (!address || !text.includes(SUPPORT_EMAIL_TOKEN)) {
    return text;
  }
  return text.split(SUPPORT_EMAIL_TOKEN).map((part, index) => (
    <React.Fragment key={`${key}-${index}`}>
      {index > 0 ? (
        <Text style={styles.link} accessibilityRole="link" onPress={() => openUrl(`mailto:${address}`)}>
          {address}
        </Text>
      ) : null}
      {part}
    </React.Fragment>
  ));
}

function renderSpans(spans: Span[], blockKey: string): React.ReactNode[] {
  return spans.map((span, index) => {
    const key = `${blockKey}-${index}`;
    switch (span.kind) {
      case 'bold':
        return (
          <Text key={key} style={styles.bold}>
            {renderText(span.text, key)}
          </Text>
        );
      case 'route':
        return (
          <Text key={key} style={styles.link} accessibilityRole="link" onPress={() => router.push(span.href as never)}>
            {span.text}
          </Text>
        );
      case 'url':
        return (
          <Text key={key} style={styles.link} accessibilityRole="link" onPress={() => openUrl(span.href)}>
            {span.text}
          </Text>
        );
      default:
        return <React.Fragment key={key}>{renderText(span.text, key)}</React.Fragment>;
    }
  });
}

export default function TermsOfUseScreen() {
  return (
    <>
      <Stack.Screen options={{ title: TITLE }} />
      <ScrollView style={styles.scroll} contentContainerStyle={styles.container}>
        <Text style={styles.updated}>Last updated: {UPDATED}</Text>
        {CONTENT.map((block, index) => {
          const key = `b${index}`;
          if (block.type === 'h2' || block.type === 'h3') {
            return (
              <Text key={key} style={block.type === 'h2' ? styles.h2 : styles.h3} accessibilityRole="header">
                {renderSpans(block.spans, key)}
              </Text>
            );
          }
          if (block.type === 'li') {
            return (
              <View key={key} style={styles.listItem}>
                <Text style={styles.bullet} importantForAccessibility="no" accessibilityElementsHidden>
                  •
                </Text>
                <Text style={[styles.body, styles.listText]}>{renderSpans(block.spans, key)}</Text>
              </View>
            );
          }
          return (
            <Text key={key} style={styles.body}>
              {renderSpans(block.spans, key)}
            </Text>
          );
        })}
      </ScrollView>
    </>
  );
}

const styles = StyleSheet.create({
  scroll: { flex: 1, backgroundColor: colors.background },
  container: { padding: spacing.lg, paddingBottom: spacing.xxxl + spacing.xl, gap: spacing.sm },
  updated: { ...typography.label, color: colors.textSecondary, marginBottom: spacing.sm },
  h2: { ...typography.heading, color: colors.textPrimary, fontSize: 21, lineHeight: 27, marginTop: spacing.lg },
  h3: { color: colors.textPrimary, fontSize: 16, fontWeight: '800', lineHeight: 22, marginTop: spacing.sm },
  body: { color: colors.textPrimary, fontSize: 15, lineHeight: 22 },
  bold: { fontWeight: '700' },
  link: { color: colors.link, fontWeight: '600', textDecorationLine: 'underline' },
  listItem: { flexDirection: 'row', gap: spacing.sm, paddingLeft: spacing.xs },
  bullet: { color: colors.textPrimary, fontSize: 15, lineHeight: 22 },
  listText: { flex: 1 },
});
